---
abstract: 'Perl interface to the 2.x series of the GNOME VFS library'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132661'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gnome2-VFS
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::Depends: 0.20
  ExtUtils::PkgConfig: 1.03
  Glib: 1.120
version: 1.082
